# Generated by Django 5.1.1 on 2024-11-14 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_published_at_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-published_at']},
        ),
    ]
