# Generated by Django 5.1.1 on 2024-11-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpost_published_at_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
