# Generated by Django 5.1.1 on 2024-11-18 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog_app.blogpost'),
        ),
    ]
